### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codetanmoy**

### CODE REVIEW

**Comment by RCMainak** [comment]
Hey @codetanmoy, do you need help to resolve the merge conflict? 

Btw, can we organize nodeschool events in kolkata? Maybe in near future?

**Comment by codetanmoy** [comment]
It's already resolved. Yes, we are planning to do it in August.

**Comment by RCMainak** [comment]
In that case I would like to help organize the event.

**Comment by koustuvsinha** [comment]
closing this PR

**Pull request closed without merging**
